# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2026-01-02 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=27)),
                ('Last_Name', models.CharField(max_length=27)),
                ('Username', models.CharField(max_length=27)),
                ('P1', models.CharField(max_length=17)),
                ('P2', models.CharField(max_length=17)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Mobile_Number', models.CharField(max_length=15)),
            ],
        ),
    ]
